#
# Module manifest for module 'NICOTroubleshooting'
#
# Generated by: Ferdi Keijzer
#
# Generated on: 5/16/2025
#

@{

    # Script module or binary module file associated with this manifest.
    RootModule           = 'NICOTroubleshooting.psm1'

    # Version number of this module.
    ModuleVersion        = '1.0.0'

    # Supported PSEditions
    CompatiblePSEditions = @('Desktop', 'Core')

    # ID used to uniquely identify this module
    GUID                 = '42dfc4d2-c62c-4838-a97d-ddb06f7cb701'

    # Author of this module
    Author               = 'Ferdi Keijzer'

    # Company or vendor of this module
    CompanyName          = 'National Indemnity Company'

    # Copyright statement for this module
    Copyright            = '(c) Ferdi Keijzer. All rights reserved.'

    # Description of the functionality provided by this module
    Description          = 'Custom functions for troubleshooting common issues'

    # Minimum version of the PowerShell engine required by this module
    PowerShellVersion    = '5.1'

    # Modules that must be imported into the global environment prior to importing this module
    RequiredModules      = @()

    # Assemblies that must be loaded prior to importing this module
    RequiredAssemblies   = @()

    # Script files (.ps1) that are run in the caller's environment prior to importing this module.
    ScriptsToProcess     = @()

    # Type files (.ps1xml) to be loaded when importing this module
    TypesToProcess       = @()

    # Format files (.ps1xml) to be loaded when importing this module
    FormatsToProcess     = @()

    # Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
    NestedModules        = @()

    # Functions to export from this module
    FunctionsToExport    = @(
        'Expand-WindowsUpdatePackage',
        'Get-PackageByBuild',
        'Install-Packages',
        'Invoke-Signcode',
        'Install-PendingUpdates',
        'Remove-UnusedLanguages',
        'Restore-CPSAssemblies',
        'Start-MachinePolicyUpdate',
        'Suspend-EPM',
        'Test-TIStatus'
    )

    # Cmdlets to export from this module
    CmdletsToExport      = @()

    # Variables to export from this module
    VariablesToExport    = @()

    # Aliases to export from this module
    AliasesToExport      = @()

    # DSC resources to export from this module
    DscResourcesToExport = @()

    # List of all modules packaged with this module
    ModuleList           = @()

    # List of all files packaged with this module
    FileList             = @()

    # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData          = @{

        PSData = @{

            # Tags applied to this module. These help with module discovery in online galleries.
            Tags                       = @('Troubleshooting', 'PowerShell', 'Updates', 'Packages')

            # A URL to the license for this module.
            LicenseUri                 = 'https://example.com/license'

            # A URL to the main website for this project.
            ProjectUri                 = 'https://example.com/project'

            # A URL to an icon representing this module.
            IconUri                    = 'https://example.com/icon'

            # ReleaseNotes of this module
            ReleaseNotes               = 'Initial release of NICOTroubleshooting module with functions for package management and troubleshooting.'

            # Prerelease string of this module
            # Prerelease = ''

            # Flag to indicate whether the module requires explicit user acceptance for install/update/save
            RequireLicenseAcceptance   = $false

            # External dependent modules of this module
            ExternalModuleDependencies = @()

        } # End of PSData hashtable

    } # End of PrivateData hashtable

    # HelpInfo URI of this module
    HelpInfoURI          = 'https://example.com/help'

    # Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
    DefaultCommandPrefix = ''

}

# SIG # Begin signature block
# MIIqAQYJKoZIhvcNAQcCoIIp8jCCKe4CAQExDzANBglghkgBZQMEAgEFADB5Bgor
# BgEEAYI3AgEEoGswaTA0BgorBgEEAYI3AgEeMCYCAwEAAAQQH8w7YFlLCE63JNLG
# KX7zUQIBAAIBAAIBAAIBAAIBADAxMA0GCWCGSAFlAwQCAQUABCCBwIyXLzm1ORkk
# 9se/4feyXJ7CfgurGS8kezDSjsNudqCCIxIwggWNMIIEdaADAgECAhAOmxiO+dAt
# 5+/bUOIIQBhaMA0GCSqGSIb3DQEBDAUAMGUxCzAJBgNVBAYTAlVTMRUwEwYDVQQK
# EwxEaWdpQ2VydCBJbmMxGTAXBgNVBAsTEHd3dy5kaWdpY2VydC5jb20xJDAiBgNV
# BAMTG0RpZ2lDZXJ0IEFzc3VyZWQgSUQgUm9vdCBDQTAeFw0yMjA4MDEwMDAwMDBa
# Fw0zMTExMDkyMzU5NTlaMGIxCzAJBgNVBAYTAlVTMRUwEwYDVQQKEwxEaWdpQ2Vy
# dCBJbmMxGTAXBgNVBAsTEHd3dy5kaWdpY2VydC5jb20xITAfBgNVBAMTGERpZ2lD
# ZXJ0IFRydXN0ZWQgUm9vdCBHNDCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoC
# ggIBAL/mkHNo3rvkXUo8MCIwaTPswqclLskhPfKK2FnC4SmnPVirdprNrnsbhA3E
# MB/zG6Q4FutWxpdtHauyefLKEdLkX9YFPFIPUh/GnhWlfr6fqVcWWVVyr2iTcMKy
# unWZanMylNEQRBAu34LzB4TmdDttceItDBvuINXJIB1jKS3O7F5OyJP4IWGbNOsF
# xl7sWxq868nPzaw0QF+xembud8hIqGZXV59UWI4MK7dPpzDZVu7Ke13jrclPXuU1
# 5zHL2pNe3I6PgNq2kZhAkHnDeMe2scS1ahg4AxCN2NQ3pC4FfYj1gj4QkXCrVYJB
# MtfbBHMqbpEBfCFM1LyuGwN1XXhm2ToxRJozQL8I11pJpMLmqaBn3aQnvKFPObUR
# WBf3JFxGj2T3wWmIdph2PVldQnaHiZdpekjw4KISG2aadMreSx7nDmOu5tTvkpI6
# nj3cAORFJYm2mkQZK37AlLTSYW3rM9nF30sEAMx9HJXDj/chsrIRt7t/8tWMcCxB
# YKqxYxhElRp2Yn72gLD76GSmM9GJB+G9t+ZDpBi4pncB4Q+UDCEdslQpJYls5Q5S
# UUd0viastkF13nqsX40/ybzTQRESW+UQUOsxxcpyFiIJ33xMdT9j7CFfxCBRa2+x
# q4aLT8LWRV+dIPyhHsXAj6KxfgommfXkaS+YHS312amyHeUbAgMBAAGjggE6MIIB
# NjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBTs1+OC0nFdZEzfLmc/57qYrhwP
# TzAfBgNVHSMEGDAWgBRF66Kv9JLLgjEtUYunpyGd823IDzAOBgNVHQ8BAf8EBAMC
# AYYweQYIKwYBBQUHAQEEbTBrMCQGCCsGAQUFBzABhhhodHRwOi8vb2NzcC5kaWdp
# Y2VydC5jb20wQwYIKwYBBQUHMAKGN2h0dHA6Ly9jYWNlcnRzLmRpZ2ljZXJ0LmNv
# bS9EaWdpQ2VydEFzc3VyZWRJRFJvb3RDQS5jcnQwRQYDVR0fBD4wPDA6oDigNoY0
# aHR0cDovL2NybDMuZGlnaWNlcnQuY29tL0RpZ2lDZXJ0QXNzdXJlZElEUm9vdENB
# LmNybDARBgNVHSAECjAIMAYGBFUdIAAwDQYJKoZIhvcNAQEMBQADggEBAHCgv0Nc
# Vec4X6CjdBs9thbX979XB72arKGHLOyFXqkauyL4hxppVCLtpIh3bb0aFPQTSnov
# Lbc47/T/gLn4offyct4kvFIDyE7QKt76LVbP+fT3rDB6mouyXtTP0UNEm0Mh65Zy
# oUi0mcudT6cGAxN3J0TU53/oWajwvy8LpunyNDzs9wPHh6jSTEAZNUZqaVSwuKFW
# juyk1T3osdz9HNj0d1pcVIxv76FQPfx2CWiEn2/K2yCNNWAcAgPLILCsWKAOQGPF
# mCLBsln1VWvPJ6tsds5vIy30fnFqI2si/xK4VC0nftg62fC2h5b9W9FcrBjDTZ9z
# twGpn1eqXijiuZQwggauMIIElqADAgECAhAHNje3JFR82Ees/ShmKl5bMA0GCSqG
# SIb3DQEBCwUAMGIxCzAJBgNVBAYTAlVTMRUwEwYDVQQKEwxEaWdpQ2VydCBJbmMx
# GTAXBgNVBAsTEHd3dy5kaWdpY2VydC5jb20xITAfBgNVBAMTGERpZ2lDZXJ0IFRy
# dXN0ZWQgUm9vdCBHNDAeFw0yMjAzMjMwMDAwMDBaFw0zNzAzMjIyMzU5NTlaMGMx
# CzAJBgNVBAYTAlVTMRcwFQYDVQQKEw5EaWdpQ2VydCwgSW5jLjE7MDkGA1UEAxMy
# RGlnaUNlcnQgVHJ1c3RlZCBHNCBSU0E0MDk2IFNIQTI1NiBUaW1lU3RhbXBpbmcg
# Q0EwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQDGhjUGSbPBPXJJUVXH
# JQPE8pE3qZdRodbSg9GeTKJtoLDMg/la9hGhRBVCX6SI82j6ffOciQt/nR+eDzMf
# UBMLJnOWbfhXqAJ9/UO0hNoR8XOxs+4rgISKIhjf69o9xBd/qxkrPkLcZ47qUT3w
# 1lbU5ygt69OxtXXnHwZljZQp09nsad/ZkIdGAHvbREGJ3HxqV3rwN3mfXazL6IRk
# tFLydkf3YYMZ3V+0VAshaG43IbtArF+y3kp9zvU5EmfvDqVjbOSmxR3NNg1c1eYb
# qMFkdECnwHLFuk4fsbVYTXn+149zk6wsOeKlSNbwsDETqVcplicu9Yemj052FVUm
# cJgmf6AaRyBD40NjgHt1biclkJg6OBGz9vae5jtb7IHeIhTZgirHkr+g3uM+onP6
# 5x9abJTyUpURK1h0QCirc0PO30qhHGs4xSnzyqqWc0Jon7ZGs506o9UD4L/wojzK
# QtwYSH8UNM/STKvvmz3+DrhkKvp1KCRB7UK/BZxmSVJQ9FHzNklNiyDSLFc1eSuo
# 80VgvCONWPfcYd6T/jnA+bIwpUzX6ZhKWD7TA4j+s4/TXkt2ElGTyYwMO1uKIqjB
# Jgj5FBASA31fI7tk42PgpuE+9sJ0sj8eCXbsq11GdeJgo1gJASgADoRU7s7pXche
# MBK9Rp6103a50g5rmQzSM7TNsQIDAQABo4IBXTCCAVkwEgYDVR0TAQH/BAgwBgEB
# /wIBADAdBgNVHQ4EFgQUuhbZbU2FL3MpdpovdYxqII+eyG8wHwYDVR0jBBgwFoAU
# 7NfjgtJxXWRM3y5nP+e6mK4cD08wDgYDVR0PAQH/BAQDAgGGMBMGA1UdJQQMMAoG
# CCsGAQUFBwMIMHcGCCsGAQUFBwEBBGswaTAkBggrBgEFBQcwAYYYaHR0cDovL29j
# c3AuZGlnaWNlcnQuY29tMEEGCCsGAQUFBzAChjVodHRwOi8vY2FjZXJ0cy5kaWdp
# Y2VydC5jb20vRGlnaUNlcnRUcnVzdGVkUm9vdEc0LmNydDBDBgNVHR8EPDA6MDig
# NqA0hjJodHRwOi8vY3JsMy5kaWdpY2VydC5jb20vRGlnaUNlcnRUcnVzdGVkUm9v
# dEc0LmNybDAgBgNVHSAEGTAXMAgGBmeBDAEEAjALBglghkgBhv1sBwEwDQYJKoZI
# hvcNAQELBQADggIBAH1ZjsCTtm+YqUQiAX5m1tghQuGwGC4QTRPPMFPOvxj7x1Bd
# 4ksp+3CKDaopafxpwc8dB+k+YMjYC+VcW9dth/qEICU0MWfNthKWb8RQTGIdDAiC
# qBa9qVbPFXONASIlzpVpP0d3+3J0FNf/q0+KLHqrhc1DX+1gtqpPkWaeLJ7giqzl
# /Yy8ZCaHbJK9nXzQcAp876i8dU+6WvepELJd6f8oVInw1YpxdmXazPByoyP6wCeC
# RK6ZJxurJB4mwbfeKuv2nrF5mYGjVoarCkXJ38SNoOeY+/umnXKvxMfBwWpx2cYT
# gAnEtp/Nh4cku0+jSbl3ZpHxcpzpSwJSpzd+k1OsOx0ISQ+UzTl63f8lY5knLD0/
# a6fxZsNBzU+2QJshIUDQtxMkzdwdeDrknq3lNHGS1yZr5Dhzq6YBT70/O3itTK37
# xJV77QpfMzmHQXh6OOmc4d0j/R0o08f56PGYX/sr2H7yRp11LB4nLCbbbxV7HhmL
# NriT1ObyF5lZynDwN7+YAN8gFk8n+2BnFqFmut1VwDophrCYoCvtlUG3OtUVmDG0
# YgkPCr2B2RP+v6TR81fZvAT6gt4y3wSJ8ADNXcL50CN/AAvkdgIm2fBldkKmKYcJ
# RyvmfxqkhQ/8mJb2VVQrH4D6wPIOK+XW+6kvRBVK5xMOHds3OBqhK/bt1nz8MIIG
# vDCCBKSgAwIBAgIQC65mvFq6f5WHxvnpBOMzBDANBgkqhkiG9w0BAQsFADBjMQsw
# CQYDVQQGEwJVUzEXMBUGA1UEChMORGlnaUNlcnQsIEluYy4xOzA5BgNVBAMTMkRp
# Z2lDZXJ0IFRydXN0ZWQgRzQgUlNBNDA5NiBTSEEyNTYgVGltZVN0YW1waW5nIENB
# MB4XDTI0MDkyNjAwMDAwMFoXDTM1MTEyNTIzNTk1OVowQjELMAkGA1UEBhMCVVMx
# ETAPBgNVBAoTCERpZ2lDZXJ0MSAwHgYDVQQDExdEaWdpQ2VydCBUaW1lc3RhbXAg
# MjAyNDCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAL5qc5/2lSGrljC6
# W23mWaO16P2RHxjEiDtqmeOlwf0KMCBDEr4IxHRGd7+L660x5XltSVhhK64zi9Ce
# C9B6lUdXM0s71EOcRe8+CEJp+3R2O8oo76EO7o5tLuslxdr9Qq82aKcpA9O//X6Q
# E+AcaU/byaCagLD/GLoUb35SfWHh43rOH3bpLEx7pZ7avVnpUVmPvkxT8c2a2yC0
# WMp8hMu60tZR0ChaV76Nhnj37DEYTX9ReNZ8hIOYe4jl7/r419CvEYVIrH6sN00y
# x49boUuumF9i2T8UuKGn9966fR5X6kgXj3o5WHhHVO+NBikDO0mlUh902wS/Eeh8
# F/UFaRp1z5SnROHwSJ+QQRZ1fisD8UTVDSupWJNstVkiqLq+ISTdEjJKGjVfIcsg
# A4l9cbk8Smlzddh4EfvFrpVNnes4c16Jidj5XiPVdsn5n10jxmGpxoMc6iPkoaDh
# i6JjHd5ibfdp5uzIXp4P0wXkgNs+CO/CacBqU0R4k+8h6gYldp4FCMgrXdKWfM4N
# 0u25OEAuEa3JyidxW48jwBqIJqImd93NRxvd1aepSeNeREXAu2xUDEW8aqzFQDYm
# r9ZONuc2MhTMizchNULpUEoA6Vva7b1XCB+1rxvbKmLqfY/M/SdV6mwWTyeVy5Z/
# JkvMFpnQy5wR14GJcv6dQ4aEKOX5AgMBAAGjggGLMIIBhzAOBgNVHQ8BAf8EBAMC
# B4AwDAYDVR0TAQH/BAIwADAWBgNVHSUBAf8EDDAKBggrBgEFBQcDCDAgBgNVHSAE
# GTAXMAgGBmeBDAEEAjALBglghkgBhv1sBwEwHwYDVR0jBBgwFoAUuhbZbU2FL3Mp
# dpovdYxqII+eyG8wHQYDVR0OBBYEFJ9XLAN3DigVkGalY17uT5IfdqBbMFoGA1Ud
# HwRTMFEwT6BNoEuGSWh0dHA6Ly9jcmwzLmRpZ2ljZXJ0LmNvbS9EaWdpQ2VydFRy
# dXN0ZWRHNFJTQTQwOTZTSEEyNTZUaW1lU3RhbXBpbmdDQS5jcmwwgZAGCCsGAQUF
# BwEBBIGDMIGAMCQGCCsGAQUFBzABhhhodHRwOi8vb2NzcC5kaWdpY2VydC5jb20w
# WAYIKwYBBQUHMAKGTGh0dHA6Ly9jYWNlcnRzLmRpZ2ljZXJ0LmNvbS9EaWdpQ2Vy
# dFRydXN0ZWRHNFJTQTQwOTZTSEEyNTZUaW1lU3RhbXBpbmdDQS5jcnQwDQYJKoZI
# hvcNAQELBQADggIBAD2tHh92mVvjOIQSR9lDkfYR25tOCB3RKE/P09x7gUsmXqt4
# 0ouRl3lj+8QioVYq3igpwrPvBmZdrlWBb0HvqT00nFSXgmUrDKNSQqGTdpjHsPy+
# LaalTW0qVjvUBhcHzBMutB6HzeledbDCzFzUy34VarPnvIWrqVogK0qM8gJhh/+q
# DEAIdO/KkYesLyTVOoJ4eTq7gj9UFAL1UruJKlTnCVaM2UeUUW/8z3fvjxhN6hdT
# 98Vr2FYlCS7Mbb4Hv5swO+aAXxWUm3WpByXtgVQxiBlTVYzqfLDbe9PpBKDBfk+r
# abTFDZXoUke7zPgtd7/fvWTlCs30VAGEsshJmLbJ6ZbQ/xll/HjO9JbNVekBv2Tg
# em+mLptR7yIrpaidRJXrI+UzB6vAlk/8a1u7cIqV0yef4uaZFORNekUgQHTqddms
# PCEIYQP7xGxZBIhdmm4bhYsVA6G2WgNFYagLDBzpmk9104WQzYuVNsxyoVLObhx3
# RugaEGru+SojW4dHPoWrUhftNpFC5H7QEY7MhKRyrBe7ucykW7eaCuWBsBb4HOKR
# FVDcrZgdwaSIqMDiCLg4D+TPVgKx2EgEdeoHNHT9l3ZDBD+XgbF+23/zBjeCtxz+
# dL/9NWR6P2eZRi7zcEO1xwcdcqJsyz/JceENc2Sg8h3KeFUCS7tpFk7CrDqkMIIH
# tDCCBZygAwIBAgITaQAAAAl2gvY2QujzQwAAAAAACTANBgkqhkiG9w0BAQsFADBW
# MRUwEwYKCZImiZPyLGQBGRYFbG9jYWwxFjAUBgoJkiaJk/IsZAEZFgZuaWNvYWQx
# JTAjBgNVBAMTHE5hdGlvbmFsIEluZGVtbml0eSBDQSAtIFJvb3QwHhcNMTcwNzE5
# MTYxMzU2WhcNMjcwNzE3MTYxMzU2WjBYMRUwEwYKCZImiZPyLGQBGRYFbG9jYWwx
# FjAUBgoJkiaJk/IsZAEZFgZuaWNvYWQxJzAlBgNVBAMTHk5hdGlvbmFsIEluZGVt
# bml0eSBDQSAtIFN1YkNBMTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIB
# AMhDueGTQHIgEiBTvBprxrBv6dtv7gDGK71RmX6uoZC4XDFPAYDvZSqx0A5hSP3V
# l+F+Ir2Y7wNNS2tOC8T1ZOYac+SIWcfb4bJlhRE2tlSWiJoS/YvObn66vgB7vJ15
# kbrH7+u72sY6NC0l7dm1+b0JdcZ/Klmd6u6y9r5gKKF4CA2YsCjRRH2UDKdjhiMk
# uQni6owg/MeS0DtBbyCoM3hd2Xycwt88quoKc+4wWD3EasrmnDBzV9GC4QIavAJQ
# 5xoiSISZPoVKKD8empqum3dG5LJp2e+t6yFXsgCN7oLyXSlj0p2tVfGuDAozt//g
# KYVbBiJ42/v4zir3SIUy0CzvhEKcurAHCoF9nFMKESKcDNSxNqFmTx92csVt7TFt
# 7B8KIcnJDdEzqsHzSjunPu62+bDUJknLHjfGz2yKov6nJ0t+NTyNcYx9iOxi4VtJ
# YIegwEsNvvF4t5lJkDNo/+qczajgj9Z8yhQmMV9rTpzxbeXUVpS35O86oVaz7mK+
# e6RgybP0ffifIqJfTWVlN0ctN+F3q9Z/04N01PAXztmyLGqgUJQz1Fl0DPTS0q32
# 4Vo4sCR/u9sZQGjMzBqJh9pq4ThopTK59LCMVxriyv9fIkLPdCT13TR3jxl5Q2kA
# lVo+UfPggdsZHGT74qu0UQ50FEZlZXVA11Vy4NqIod67AgMBAAGjggJ3MIICczAQ
# BgkrBgEEAYI3FQEEAwIBADAdBgNVHQ4EFgQUNxuin97xSd/IPTc0wNwAqmSKau4w
# PgYJKwYBBAGCNxUHBDEwLwYnKwYBBAGCNxUIh6WEdIOVjzKH6Z0rh4LXBoaJ0BCB
# D4eNs26Bo6IqAgFkAgEFMAsGA1UdDwQEAwIBhjAPBgNVHRMBAf8EBTADAQH/MB8G
# A1UdIwQYMBaAFLhhhzkVdHQNDebZilc8jIq4VoAdMIHmBgNVHR8Egd4wgdswgdig
# gdWggdKGgc9sZGFwOi8vL0NOPU5hdGlvbmFsJTIwSW5kZW1uaXR5JTIwQ0ElMjAt
# JTIwUm9vdCxDTj1OaWNvQ2VydDAxLENOPUNEUCxDTj1QdWJsaWMlMjBLZXklMjBT
# ZXJ2aWNlcyxDTj1TZXJ2aWNlcyxDTj1Db25maWd1cmF0aW9uLERDPW5pY29hZCxE
# Qz1sb2NhbD9jZXJ0aWZpY2F0ZVJldm9jYXRpb25MaXN0P2Jhc2U/b2JqZWN0Q2xh
# c3M9Y1JMRGlzdHJpYnV0aW9uUG9pbnQwgdcGCCsGAQUFBwEBBIHKMIHHMIHEBggr
# BgEFBQcwAoaBt2xkYXA6Ly8vQ049TmF0aW9uYWwlMjBJbmRlbW5pdHklMjBDQSUy
# MC0lMjBSb290LENOPUFJQSxDTj1QdWJsaWMlMjBLZXklMjBTZXJ2aWNlcyxDTj1T
# ZXJ2aWNlcyxDTj1Db25maWd1cmF0aW9uLERDPW5pY29hZCxEQz1sb2NhbD9jQUNl
# cnRpZmljYXRlP2Jhc2U/b2JqZWN0Q2xhc3M9Y2VydGlmaWNhdGlvbkF1dGhvcml0
# eTANBgkqhkiG9w0BAQsFAAOCAgEASXh2w5YfhYHnjupbLgpm7ViWaMYC3meArxW+
# JNsht/sdeikyKqWwTc3VDQgI++7Npe2Q+BCN4VhBBjf7cc8qD611c5AeL9deBz2O
# eo35Eysa06c+SyfB2Wg9mjHEwrvKQTTdtfOm2OKOyjTeR/9XIbftgLth/1RrH9EL
# e/GScHVjc9ywX2VXUDtL9b3TWaYYgT7dDfbYHtWHQwZ52GqwVD2QkX0Y5QuIiS48
# S0Fs48vSDwM+mCGa8MeKPkw112+fOYBd+fY3jK6Ssgu7NO1EUNZsI3jfM6lbHxv3
# +v5s66xf/rg9UAo0XfFLiSEM758NlDm7PfN154iZudlxbvrcip9sObffTO+Po1R3
# aWSBJxLBzhWHcoZ8s9yp/uLShwJ3ByNrwWhNakjdUMbZo9c2mEfSOOmjxd37iaP5
# YEy4j9s7Fu/DN4SVA9hXcyW8CuVyMBdVBOmJKwjDIb25DleQmDmxP2euvXFnAGFh
# 1DzvLFF0xPqnTclan5Qfe+NJdBO3rdBzCghgmuXoocQkVuonjRcHAVeWQI+uPIJ5
# GFsSW6jev/+Qp8EK0gugEZwq1kFx9dzJyqkg+3xv50s1x71isLlfYw8smICuyEUn
# zEbiv8Lj80ToZVNjD/vgUvm7G4dxt85xvVsqf1TMRKN9QCYGmlRDa/U/7J5DvWSA
# +dPoMdMwgghTMIIGO6ADAgECAhNXAABkdjbpivbBR9RNAAAAAGR2MA0GCSqGSIb3
# DQEBCwUAMFgxFTATBgoJkiaJk/IsZAEZFgVsb2NhbDEWMBQGCgmSJomT8ixkARkW
# Bm5pY29hZDEnMCUGA1UEAxMeTmF0aW9uYWwgSW5kZW1uaXR5IENBIC0gU3ViQ0Ex
# MB4XDTIyMDgyOTE1MzUyMloXDTI1MDgyODE1MzUyMlowgbgxCzAJBgNVBAYTAlVT
# MQswCQYDVQQIEwJORTEOMAwGA1UEBxMFT21haGExIzAhBgNVBAoTGk5hdGlvbmFs
# IEluZGVtbml0eSBDb21wYW55MRUwEwYDVQQLEwxTZXJ2aWNlIFRlYW0xJTAjBgNV
# BAMTHFNlcnZpY2VUZWFtUG93ZXJzaGVsbFNpZ25pbmcxKTAnBgkqhkiG9w0BCQEW
# GmNlcnRAbmF0aW9uYWxpbmRlbW5pdHkuY29tMIICIjANBgkqhkiG9w0BAQEFAAOC
# Ag8AMIICCgKCAgEAj1IOtYwrNx8G8+jW8LamirmlJ1SAXLj7J3oAfiKyi/RmHC6c
# Ci4mkeppWT9NsAz3RQCu9B1i67semOvhJeCFDUF6OuQEGNtnXPakqcfoJxSl5/r+
# 1m5tjHpqFQpyMBx5pEviK3kh0PZTSMwbm134YLo3blWRY5n/dkUZ/yz95/mx9NDv
# EMABEwEtRA+jJBsYTUVxXQXkcYs59SOMaUkoar04CG8PAohMPbAxpswducedOzDG
# i/R1+oTzLMfZDNGBnDhZXhtKIPO9HxIjySpJ9C+AwzskEl6oWHWu5v/Erl3w5yNd
# MwJwQXSWGv0j6ubw8aYgbpHaaP8vG1aqkUavZxPlCvCoD/PnyCMs5xPwgXxXmSHq
# TWxF7hUtG7R54gW8Dr2AZsDKYk6uQ2Rz+wJcREyqZF2q+UPYNLVVOKQyBB67pmVj
# wmZSFzHIirgv8GyYf1OIbMFh9VkUjP4E0IW/HzBMg2YaCtxWQ0uwHY/ntMP2AY/V
# tVOYQlphkD6tK8c0TQKLAUxB4M+VS27Mu3zmdl7Tqxok0qtXzAnIO4jaidc7rq5V
# Xd/U0Gvz9AFKhqooMNZSFdpKey6+bQ9yKjusFHeEkHcpwxX4kCERwVTtUJnQKHmf
# E4XNG86+C0vAZtvY27IdiQC+EQb2WObQ3m/PPzCda/aaEw4+R9Lp5lEEOxUCAwEA
# AaOCArMwggKvMAsGA1UdDwQEAwIF4DATBgNVHSUEDDAKBggrBgEFBQcDAzAnBgNV
# HREEIDAeghxTZXJ2aWNlVGVhbVBvd2Vyc2hlbGxTaWduaW5nMB0GA1UdDgQWBBSB
# P51jNehJkhPjkmxqv1E1hYjLLTAfBgNVHSMEGDAWgBQ3G6Kf3vFJ38g9NzTA3ACq
# ZIpq7jCB6AYDVR0fBIHgMIHdMIHaoIHXoIHUhoHRbGRhcDovLy9DTj1OYXRpb25h
# bCUyMEluZGVtbml0eSUyMENBJTIwLSUyMFN1YkNBMSxDTj1OaWNvQ2VydDA1LENO
# PUNEUCxDTj1QdWJsaWMlMjBLZXklMjBTZXJ2aWNlcyxDTj1TZXJ2aWNlcyxDTj1D
# b25maWd1cmF0aW9uLERDPW5pY29hZCxEQz1sb2NhbD9jZXJ0aWZpY2F0ZVJldm9j
# YXRpb25MaXN0P2Jhc2U/b2JqZWN0Q2xhc3M9Y1JMRGlzdHJpYnV0aW9uUG9pbnQw
# gdkGCCsGAQUFBwEBBIHMMIHJMIHGBggrBgEFBQcwAoaBuWxkYXA6Ly8vQ049TmF0
# aW9uYWwlMjBJbmRlbW5pdHklMjBDQSUyMC0lMjBTdWJDQTEsQ049QUlBLENOPVB1
# YmxpYyUyMEtleSUyMFNlcnZpY2VzLENOPVNlcnZpY2VzLENOPUNvbmZpZ3VyYXRp
# b24sREM9bmljb2FkLERDPWxvY2FsP2NBQ2VydGlmaWNhdGU/YmFzZT9vYmplY3RD
# bGFzcz1jZXJ0aWZpY2F0aW9uQXV0aG9yaXR5MD4GCSsGAQQBgjcVBwQxMC8GJysG
# AQQBgjcVCIelhHSDlY8yh+mdK4eC1waGidAQgQ+Fp8k4hPHSKgIBZAIBDjAbBgkr
# BgEEAYI3FQoEDjAMMAoGCCsGAQUFBwMDMA0GCSqGSIb3DQEBCwUAA4ICAQBZpTGi
# DdGjn9KHpUwNSTZ82wNpNrdZkN+a31aM8D24ejZsZIhm/RIPPSDm9NZXdttzzH4x
# YuTNUVqDsxO3LoxwwFag9rO5eFv+vqHEsUV9A5eL2Cym77jVtP0XaXkamINjSfdn
# SBKZr4zELkk19mt0o7N7yTdPwtyyGTfD4RHO+aQFWaG8zymkjMyZs7s0GaQaupSf
# zPIcsz5jmP2aHthOSaBEWpq1oLdoUjKT0HgHEvCYDdIx8XWgxj1uFVtYsiPzXrDC
# Ie4agOYPTLc4sRebrI7dvBBKUuDuI/BcGHC4mwWsM1pu6xhNfDJGqedrMri4RPQD
# azVsEMQ4zGJzHw4+wojs9poPA3oTA2z3rDeZ5OLxJTUSLo3CBOFEIiEzyCk01Qbn
# PP9hc9Gn/yIW0MP7P7sIiidj1n5MH97ZkxBkRvVHTtrvZrF4zwef3d0CbuOj/OJA
# nwx4RwmWd9EuU6mSLizVakP+fFG02pbdvYpBVl5eZTRTKH1FM2FpWl+NO2sSa3OJ
# HfzVxBorKDcT04aJNQesNprEZhBhNPqYN6UORBtEYjhVyL0jPCHiUTSdvHgvOysj
# DEPiT5BpJGXwl9MwyQbSGJaRSjkLn/EYH7fwCBK6BlOY60WI4A4g/uTjzCV0jVfE
# IH2/9xeyeJVN2y3ISHGuWGFNC8eIQvo1xIYacDGCBkUwggZBAgEBMG8wWDEVMBMG
# CgmSJomT8ixkARkWBWxvY2FsMRYwFAYKCZImiZPyLGQBGRYGbmljb2FkMScwJQYD
# VQQDEx5OYXRpb25hbCBJbmRlbW5pdHkgQ0EgLSBTdWJDQTECE1cAAGR2NumK9sFH
# 1E0AAAAAZHYwDQYJYIZIAWUDBAIBBQCggYQwGAYKKwYBBAGCNwIBDDEKMAigAoAA
# oQKAADAZBgkqhkiG9w0BCQMxDAYKKwYBBAGCNwIBBDAcBgorBgEEAYI3AgELMQ4w
# DAYKKwYBBAGCNwIBFTAvBgkqhkiG9w0BCQQxIgQgZfMMW0YPQMPBndIom58AEwTn
# wfiR1fCqrrQTN06KwSMwDQYJKoZIhvcNAQEBBQAEggIAc4ZF4KUEJovLoyoUW5W5
# DUM3EvryUFXyXNMM0dC/VfGJ1ZYbX3RZv6i7138O2XQESvvRYhnaqfNnCbalOwCt
# 4wr3XtQyr+x6kCbN6bgjyjfHZO7GLezzA1V/tXz48cs7bcu0bCkqBvUAJfy45EKk
# zPoaE9vmgby57ATjpdZQbtDNJ2XnwiIVGB9Ddc61F23BxO3FkwhZSdHHm/+gUq05
# 8JNLrk1Ech+mhlPPa3M1xJklJqLGgOK6iId9VmJZA2xH/VaW8VUB8UWfwJXryeJu
# h7qRQkuY3TuwLzOJjH5K4nSby9IUSthr3vI6j8Rot5s+8+C5MmhGTAbI6d7t1TlS
# 2jsaJE0f/VFNhcCxo7staUWG1xPj1J4mkWZzLbtAJqJA5US9SEBRMQTfxvB+iMlf
# xDrA/khURCHHQFphRobQjXOc9qEn5WZkL411D3efq1nGp8a6GRFWVRAfjihqGInx
# Q5Q5Il3TYz84rYyONcz+3z5Cp5pKf6RCXn4vbOSCnPEH08BU4DivHyYUKPjiVPt8
# Om//FElZXT18vZxHiYz+vfaybLpd/+SEq9L1GhlberAhzB/AFi21Wn4evOwipfko
# LgIPPXmOrzsaU3fBUDl5+mZjeBSFBwHC1W4nseeitGOHjJlV70OEVRR/raoUy4Oy
# 35+f5+Y2qxeOTu5zUdqPHemhggMgMIIDHAYJKoZIhvcNAQkGMYIDDTCCAwkCAQEw
# dzBjMQswCQYDVQQGEwJVUzEXMBUGA1UEChMORGlnaUNlcnQsIEluYy4xOzA5BgNV
# BAMTMkRpZ2lDZXJ0IFRydXN0ZWQgRzQgUlNBNDA5NiBTSEEyNTYgVGltZVN0YW1w
# aW5nIENBAhALrma8Wrp/lYfG+ekE4zMEMA0GCWCGSAFlAwQCAQUAoGkwGAYJKoZI
# hvcNAQkDMQsGCSqGSIb3DQEHATAcBgkqhkiG9w0BCQUxDxcNMjUwNjA1MTY1NDI5
# WjAvBgkqhkiG9w0BCQQxIgQgA3uV/E/8oXEW7HB9Lwn2prV9gs4pf/Gigk6uOprp
# v/QwDQYJKoZIhvcNAQEBBQAEggIAAMYypsCP3Y8G/NJ62q4DEH0+kM7an/bRV5zm
# I+XXOUNZUaJiR+JvBvGZn3jbsDVJ6BkFRZoWkZs5cMwDnaagutcnEjs2mod7YmOS
# aBi/b3Xql1JURCtdtTFMFrQhjZ0IHyqtd0+3shSTME0iueMnynqPkn2RM+f6xHAF
# 6SFS6fxoG0w9hROH7db+auXNjhquWbavMxXKDxultVMw6azpgl4E8hN5becFNFga
# osTbCOGUY/1TIML7iBo7hwjCjz2IHtmMA8K1jgDTYvYCYX9bxFj7ChpAH7IgBTus
# +6Uwt1QXHNWftdY1MBKRkviphBnRFPKTpx7+V6ndyyLHw38IldYqFPU8oqDvfAV1
# rJZzCnSxlWibycPvV7QAOrTtad0ixt79Fsy+0+vGJG+wgYhxDMxxP0v2YDYUHmRi
# 7L0o5hdvXXxjTvD/TlvcFnH1gchEgiIyEd77kd3hS82290Pb+4wJvi9IIq1FZkAq
# WbaGCfWnznT2URBPhMFgH/M2amG3EWorXA8ws4pNhCGX4mAx95v43wqE0lxiUoOJ
# 0uj5yIHDOjqy/Ci11lyd1Mjj1nRO+p9HvXA0pAoltO2cnjxB0Fb3rcBMmc1B6MVJ
# FS/M6F3Vq29NtTFMLRMFwnt0b0J1Rs+kBQunV78e5Oj6h2wbzDmNO+nr5Du+wO9+
# jFKiDwA=
# SIG # End signature block
